name:          "What the heck, HTML and CSS?"
url:           http://paulmolluzzo.github.io/wth-html-css
repo:          https://github.com/paulmolluzzo/wth-html-css
twitter:       https://twitter.com/paulmolluzzo

markdown:      redcarpet
permalink:     pretty
pygments:      true
