name:          "What the heck, HTML and CSS?"
url:           http://paulmolluzzo.github.io/wth-html-css
repo:          https://github.com/paulmolluzzo/wth-html-css
twitter:       https://twitter.com/paulmolluzzo
originalurl:   http://wtfhtmlcss.com
originalrepo:  https://github.com/mdo/wtf-html-css
mdotwitter:    https://twitter.com/mdo


markdown:      redcarpet
permalink:     pretty
pygments:      true
